config/routes.rb
Questor::Application.routes.draw do

  resources :answers
  resources :questions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  match 'auth/:provider/callback', to: 'sessions#omniauth'

  resources :sessions
  resources :users

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :user_id, :question, :question_option_id

  belongs_to :user
  belongs_to :question
  belongs_to :question_option

  #validates :question, :presence => true

  #def answers_length
  #  Errors.add("answers","you must select more than 0") if self.question_option_ids.selected.count < 0
  #end
  #length of array is between min and max


end

app/models/answer_choice.rb
class AnswerChoice < ActiveRecord::Base
  attr_accessible :answer_id, :question_option_id

  belongs_to :answer
  belongs_to :question_option
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :max_selections, :min_selections, :query, :ranked, :answers, :question_options_attributes

  belongs_to :user
  has_many :question_options
  has_many :answers, :through => :question_options

  accepts_nested_attributes_for :question_options, allow_destroy: true

  validates :query, :presence => true
  validates :max_selections, :presence => true, :numericality => {only_integer: true, greater_than_or_equal_to: :min_selections}
  validates :min_selections, :presence => true, :numericality => {only_integer: true, less_than_or_equal_to: :max_selections, greater_than: 0}
  with_options :if => :ranked? do |ranked|
    ranked.validates :max_selections, :numericality => {greater_than: 1}
  end
  #validate :max_selections, :numericality => {less_than_or_equal_to: :question_options.count}
  validates_associated :question_options
end

app/models/question_option.rb
class QuestionOption < ActiveRecord::Base
  attr_accessible :description, :question_id
  belongs_to :question
  has_many :answers
  validates :description, :presence => true
  #validates_presence_of :question
end

app/models/user.rb
class User < ActiveRecord::Base
  #has_secure_password

  attr_accessible :email, :password, :password_confirmation
  has_many :questions
  has_many :answers

  validates_uniqueness_of :email

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.email = auth["info"]["email"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = current_user.answers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # POST /answers
  def create

    @formerrors = []
    question = Question.find(params[:question_id])
    max = question.max_selections
    min = question.min_selections
    if params.has_key?(:question_option_ids)
      total = params[:question_option_ids].count
      @formerrors << "You must select between #{min} and #{max} options" if ( total < min || total > max )
    else
      @formerrors << "You must select at least one option"
    end
    if @formerrors.empty?
      if current_user
        question.answers.where("user_id = ?", current_user.id).destroy_all
        params[:question_option_ids].each do |oid|
          current_user.answers.create(:question_option_id => oid)
        end
      else
        params[:question_option_ids].each do |oid|
          Answer.create(:question_option_id => oid)
        end
      end
    redirect_to action: "index", controller: "questions"
    else
      flash[:notice] = @formerrors.first
      redirect_to action: "index", controller: "questions"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/question_options_controller.rb
class QuestionOptionsController < ApplicationController

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :create, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = current_user.questions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end
  def omniauth
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Logged in!"
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/answer_choices_helper.rb
module AnswerChoicesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/question_options_helper.rb
module QuestionOptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
%html
  %head
    %title
      Questor
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        .container
          - if current_user
            Logged in as
            = current_user.email
            \.
            = link_to "Log Out", logout_path
          - else
            /= link_to "Sign Up", signup_path
            /or
            = link_to "Log in with Facebook", "auth/facebook"
    .container
      - flash.each do |name, msg|
        .alert
          = content_tag :div, msg, :id => "flash_#{name}"
      = yield

app/views/questions/_answer_options_form.haml
= form_tag("/answers", :method => "post") do
  = hidden_field_tag "question_id", question.id
  - question.question_options.each do |option|
    = check_box_tag "question_option_id", option.id
    = label_tag option.id, option.description
  = submit_tag "Vote"

app/views/questions/_form.haml
= form_for @question do |f|
  - if @question.errors.any?
    .error_messages
      %h2
        = pluralize(@question.errors.count, "error")
        prohibited this survey from being saved:
      %ul
        - @question.errors.full_messages.each do |msg|
          %li
            = msg
  .step
    %h4
      What is your Question?
    = f.text_area :query, :cols => "100", :rows => "3" 
  .step
    %h4
      What are the possible answers for your question?
    = f.fields_for :question_options do |builder|
      = render "question_option_fields", f: builder
  
    = link_to_add_fields "Add Answer", f, :question_options
  .step
    %h4
      How can others answer your question?

    = f.label :min_selections
    = f.number_field :min_selections, class: "selectnum"
    = f.label :max_selections
    = f.number_field :max_selections, class: "selectnum"
    .field
      = f.label :ranked
      = f.check_box :ranked

  #slider-range

  

  .actions
    = f.submit

app/views/questions/_question_option_fields.haml
%fieldset
  = f.label :description, "Description"
  = f.text_area :description, :cols => "100", :rows => "2" 
  = f.hidden_field :_destroy
  = link_to "remove", "#", class: "remove_fields"

app/views/questions/edit.haml
%h1
  Editing question
= render :partial => 'form'

= link_to 'Show', @question 
|
= link_to 'Back', questions_path

app/views/questions/index.haml
%h1
  Listing questions

- @questions.each do |question|
  .question
    = question.query
    %div
      %span.label
        - if question.min_selections == question.max_selections
          Choose
          = question.min_selections
        - elsif question.min_selections == 1 && question.max_selections == question.question_options.count
          - if question.ranked
            Rank
          - else
            Choose
          all that apply
        - else
          - if question.ranked
            Rank
          - else
            Choose
          between
          = question.min_selections
          and
          = question.max_selections

    = form_tag("/answers", :method => "post") do
      = hidden_field_tag "question_id", question.id
      /= hidden_field_tag "question_option_ids[]", ""
      /= hidden_field_tag "question_option_ids[]", ""
      /= hidden_field_tag "question_option_ids[]", ""
      - if question.ranked
        %ul.ranked_answers
          - question.max_selections.times do |i|
            %li.droppable
              .num
                = i+1
              .content
            .clearfix
        %ul.ranked_options
          - question.question_options.each do |option|
            %li.draggable
              .num
              .content
                = option.description
              .drag
            .clearfix
        :javascript
          $(function() {
            $( ".draggable" ).draggable();
            $( ".droppable" ).droppable({
              accept: ".draggable",
              activeClass: "ui-state-hover",
              hoverClass: "ui-state-active",
              drop: function( event, ui ) {
                $( this )
                  .addClass( "ui-state-highlight" )
              }
            });
          });
      -else
        - question.question_options.each do |option|  
          - if question.min_selections == 1 && question.max_selections == 1
            = radio_button_tag "question_option_ids[]", option.id
          - else
            = check_box_tag "question_option_ids[]", option.id
          = label_tag option.id, option.description
      = submit_tag "Vote"

    .results
      %h5
        Results
      - question.question_options.each do |option|
        %div
          %span.badge.badge-inverse
            = option.answers.count
          = option.description

    /- question.question_options.each do |option|
    /  = check_box_tag "question_option_id", option.id
    /  = label_tag option.id, option.description

    /= render "answer_options_form", :question => question
    /= render :partial => 'answers/form', :locals => {:question => question}
    .btn-group
      /= link_to 'Show', question, class: "btn"
      - if current_user
        -if question.user_id == current_user.id
          = link_to 'Edit', edit_question_path(question), class: "btn"
          = link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn"
    .clearfix
- if current_user
  = link_to 'New Question', new_question_path, class: "btn"

app/views/questions/new.haml
%h1
  New Question

= render :partial => 'form'

= link_to 'Back', questions_path

app/views/questions/show.haml
#notice
  = notice
%p
  Query:
  = @question.query
%p
  Min selections:
  = @question.min_selections
%p
  Max selections:
  = @question.max_selections
%p
  Ranked:
  = @question.ranked

= link_to 'Edit', edit_question_path(@question)
|
= link_to 'Back', questions_path

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>